/**
 * This file is generated by code generation tools.
 * Generation time is Wed Apr 12 15:37:02 CST 2017
 */
package com.flying.monitor.msg.codec;

import com.flying.common.IReturnCode;
import com.flying.monitor.model.ServerBO;
import com.flying.monitor.msg.IServerMsgType;
import com.flying.monitor.service.MonitorServiceException;
import com.flying.util.net.CommUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.UnsupportedEncodingException;
import java.util.ArrayList;
import java.util.List;

public class MonitorMsgCodec   {

//    public List<ServerBO> getServerQueryReply(byte[] bytes) throws MonitorServiceException{
//        // headerClass, varHeader, varBytes, msgTypeClass, replyClass, exception, varReply, msgDTOClass, varMsgDTO, dtoClass,
//        // stringContained, varDTOFields, varDTOs, retKindName
//        // Send and Receive the report message before timeout
//        MessageHeader header = new MessageHeader();
//        DirectBuffer replyBuffer = new DirectBuffer(bytes);
//        header.wrap(replyBuffer, 0, 0);
//        if (header.msgType() != IServerMsgType.ServerQueryReply) {
//            throw new MonitorServiceException(MonitorServiceException.MISMATCH_REPLY, "expected:" + IServerMsgType.ServerQueryReply + "actual:" + header.msgType());
//        }
//        ServerQueryReply reply = new ServerQueryReply();
//        reply.wrapForDecode(replyBuffer, header.size(), header.blockLength(), header.version());
//        if (reply.retCode() != IReturnCode.SUCCESS) {
//            throw new MonitorServiceException(reply.retCode());
//        }
//        // Analyze the reply and build the list of server bos.
//        ServerQueryReply.Servers servers = reply.servers();
//        if (servers.count() <= 0) return null;
//        List<ServerBO> serverBOs = new ArrayList<>();
//        ServerBO serverBO;
//        while (servers.hasNext()) {
//             try {
//                servers.next();
//                serverBO = new ServerBO();
//                                serverBO.setUuid(servers.getUuid());
//                serverBO.setRegion(servers.getRegion());
//                serverBO.setServiceType(servers.serviceType());
//                serverBO.setName(servers.getName());
//                serverBO.setEndpoint(servers.getEndpoint());
//                serverBO.setWorkers(servers.workers());
//                serverBO.setStateId(servers.stateId());
//                serverBO.setReportTime(servers.reportTime());
//
//                serverBOs.add(serverBO);
//            } catch (UnsupportedEncodingException uee) {
//                throw new MonitorServiceException(MonitorServiceException.FAILED_TO_BUILD_REPLY, uee);
//            }
//        }
//        return serverBOs;
//    }

}
